### ISSUE TITLE
Add toggle button to show password in Sign Up Page

### ISSUE THREAD

**Issue by hancin622** [ViviGroupe/vivicrew-web#27]

**Comment by kevinlaw91** [comment]
I once read an [article](http://www.leemunroe.com/confirm-passwords-signup/) saying that confirm password field for sign up form is actually not needed.

It makes sense actually, because if you set up a password wrongly you can use the reset password feature. This will save user time and make them happy by having less thing to fill up.

Tell me what you think...

**Comment by kevinlaw91** [comment]
If you think mistyping is still a problem, I can code something like a button to toggle show/hide password. Still better than requiring user to retype their password

**Comment by ohjacking** [comment]
hi sorry for late reply. yup go ahead with ur suggestion.
